AppBundle\Entity\ActionAccount:
    type: entity
    table: actions_accounts
    id:
        action_id:
          associationKey: true
        actor:
          type: string
        permission:
          type: string
    fields:
    manyToOne:
        action:
            targetEntity: AppBundle\Entity\Action